### ISSUE TITLE
pod lib lint warning

### ISSUE THREAD

**Issue by karlgross** [gabriel/MPMessagePack#11]
Hi Gabriel,
we are using MPMessagePack in our project. During pod lint we receive the following warning:
MPMessagePack/RPC/MPMessagePackClient.h:41:18: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]

Could you please kindly fix this warning? Thanks!

Best Regards,
Karl

**Comment by benrudhart** [comment]
I can see that this has been fixed in release `1.3.6`, but `1.3.6` is not yet available on CocoaPods (over there it's still `1.3.5`). `1.3.5` was released in Feb 2016, but this issue was only fixed in https://github.com/gabriel/MPMessagePack/commit/e7a64b9125bce2dd657dc2943dc99723dae54484  (which is from April 2016).

Would you please make a new release on CocoaPods to resolve this issue?

**Comment by gabriel** [comment]
Did new release, sorry this got lost on my radar.

**Comment by benrudhart** [comment]
Thank you 👍
