### ISSUE TITLE
Parse MessagePack Data to NSDictionary may return a NSNumber key

### ISSUE THREAD

**Issue by Blankdlh** [gabriel/MPMessagePack#2]
We request data from a php web api. In php, a string key like ‘0’ will be convert to int value, which will return NSNumber key in Objective-C. 

With Json api, the key is always a string. So maybe we can convert key to NSString ?

**Comment by gabriel** [comment]
Sorry I don't understand this issue.

**Comment by varkrishna** [comment]
<img width="515" alt="Screenshot 2022-08-01 at 12 24 56 PM" src="https://user-images.githubusercontent.com/13188037/182091454-fbe195f5-01c0-402d-8b56-a21aa6b50a03.png">

while parsing "0" it assume it as NSNumber not NSString and that is why line no 182 will execute for 0

<img width="1017" alt="Screenshot 2022-08-01 at 12 37 03 PM" src="https://user-images.githubusercontent.com/13188037/182092097-c480fe09-e08b-4b85-9b06-2b8f4cd50537.png">

 and due to this if we call _JSONSerialization.isValidJSONObject_ on unpacked object we get false.

Please Help.
